stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: fiware-draco
      pushRemote: true
      registry: 192.168.100.176:5000
timeout: 60
notification: {}
